### ISSUE TITLE
Add support for 'go check'

### ISSUE THREAD

**Issue by jszwec** [jszwec/gojunitxml#1]
Add support for 'go check'

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by ppknap** [comment]
:+1: :+1:

**Comment by rjeczalik** [comment]
:-1: 

PS I already did - [rjeczalik/ungocheck](https://github.com/rjeczalik/ungocheck) XD

```
1. Have a gocheck test.
2. Ungocheck it.
4. Have a testing output.
5. ???
6. There's no 3.
```

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
:-1:

**Comment by ppknap** [comment]
:+1:

**Comment by rjeczalik** [comment]
:-1:

**Comment by ghost** [comment]
:+1:

**Comment by ppknap** [comment]
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by rjeczalik** [comment]
:-1:

**Comment by rjeczalik** [comment]
Just to remind, :-1: and please close.

**Comment by ppknap** [comment]
Could you reopen this issue? I really need this functionality... :heart_eyes:

**Comment by rjeczalik** [comment]
![no](https://i.imgur.com/KTsywT1.gif)

**Comment by ghost** [comment]
gocheck soon will have own logic for exporting results, so whatever..
